main:
  - name: Home
    url:
    weight: 1
  - name: Blog
    url: blog/
    weight: 2
  - name: Gallery
    url: gallery/
    weight: 3
  - name: Categories
    url: categories/
    weight: 4
  - name: Tags
    url: tags/
    weight: 5
