############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Blog"
url = "blog/"
weight = 2

[[main]]
name = "Gallery"
url = "gallery/"
weight = 3

[[main]]
name = "Categories"
url = "categories/"
weight = 4

[[main]]
name = "Tags"
url = "tags/"
weight = 5

#[[main]]
#name = "About"
#url = "about/"
#weight = 6

#[[main]]
#weight = 7
#name = "Pages"
#hasChildren = true
#
#[[main]]
#parent = "Pages"
#name = "Elements"
#url = "elements/"
#
#[[main]]
#parent = "Pages"
#name = "404 Page"
#url = "404/"


# footer menu
#[[footer]]
#name = "About"
#url = "about/"
#weight = 1
#
#[[footer]]
#name = "Elements"
#url = "elements/"
#weight = 2
#
#[[footer]]
#name = "Privacy Policy"
#url = "privacy-policy/"
#weight = 3
